### ISSUE TITLE
Profiles not saving

### ISSUE THREAD

**Issue by sleewok** [SmartPack/ScreenColorControl#3]
I'm running Android 10. No profiles are listed after creating one.

**Comment by sunilpaulmathew** [comment]
Thanks for reporting. It is because I forgot to update something so that app failed to create internal folder in Android 10. I'll fix it in next update. For now, creating a folder named "ColorControl" in internal sdcard wil fix the issue.

**Comment by sleewok** [comment]
That worked. Thanks! I really like your app. I'm using it as my night time screen control to make my screen completely red.

**Comment by sunilpaulmathew** [comment]
Forgot to mention, this issue is fixed (hopefully) as of [this](https://github.com/SmartPack/ScreenColorControl/commit/c5e9f592c610845b115f1fea1bd8fe913a0a5816) commit (Included in the latest update). Hence, closing this issue.
