### ISSUE TITLE
Usability for Profile Button

### ISSUE THREAD

**Issue by sleewok** [SmartPack/ScreenColorControl#4]
Just a thought. Right now you tap a profile and it shows the text. That isn't very intuitive. I would expect tapping it would enable that profile. It seems minor, but makes a big difference.

**Comment by sunilpaulmathew** [comment]
Thanks. I'm thinking about moving that option (Details) as well into the right popup menu. What do you think?

**Comment by sleewok** [comment]
I think that would be a good idea. Tapping the button would activate. And
the other info in the pop-up.

FYI, the apply confirmation says "cancel" instead of "Okay". Another
suggestion... that confirmation should disappear if you tap anywhere.
Rather than forcing the user to press a button. They aren't making a choice
so it doesn't make much sense to force them to concentrate on the dialogue
each time.

**Comment by sunilpaulmathew** [comment]
Okay, I'll keep your suggestions on mind when I revise it.
