### ISSUE TITLE
Profile not fully taking effect on first enable.

### ISSUE THREAD

**Issue by sleewok** [SmartPack/ScreenColorControl#5]
I'm not sure if this is a problem with my ROM, or the app. I have a profile that I have to enable twice to get completely load. The first time it goes to pink, the second time to red. 

It sets the RGB to 255 35 35 on the first apply. Then 255 1 1 after the second.

Here is the profile that it saved:

`
#!/system/bin/sh

# Created by Screen Color Control

# Screen Color
echo 256 1 1 > /sys/devices/platform/kcal_ctrl.0/kcal
echo 1 > /sys/devices/platform/kcal_ctrl.0/kcal_enable
echo 1 > /sys/devices/platform/kcal_ctrl.0/kcal_min
echo 267 > /sys/devices/platform/kcal_ctrl.0/kcal_sat
echo 469 > /sys/devices/platform/kcal_ctrl.0/kcal_hue
echo 383 > /sys/devices/platform/kcal_ctrl.0/kcal_val
echo 259 > /sys/devices/platform/kcal_ctrl.0/kcal_cont

# The END
echo "Profile applied successfully..." | tee /dev/kmsg
`

**Comment by sunilpaulmathew** [comment]
I really don't know, the app will simply 'sh' the profile (basically a shell script). So, the process behind the first and second "apply' attempts are exactly the same.

**Comment by sleewok** [comment]
It sounds like it may be an issue with my kernel/ROM.
