### ISSUE TITLE
UI not reflecting values after loading profile.

### ISSUE THREAD

**Issue by sleewok** [SmartPack/ScreenColorControl#6]
After loading a profile you have to restart the app to see the updated values that are set.

**Comment by sunilpaulmathew** [comment]
Thanks for reminding me of that issue. I was aware, but, totally forgot about it. I'll look into it.

**Comment by 7sarus** [comment]
Hello, thanks for the app, I just needed to know whether there was an apk release after this solution was merged?

**Comment by sunilpaulmathew** [comment]
> Hello, thanks for the app, I just needed to know whether there was an apk release after this solution was merged?

Of course. It's available [here](https://github.com/SmartPack/ScreenColorControl/tree/master/release)...
